services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - dbsocket:/tmp # Acceso al socket compartido
    sysctls:
      - net.core.somaxconn=65535
      - net.ipv4.tcp_tw_reuse=1
      - net.ipv4.ip_local_port_range=1024 65535
      - net.ipv4.tcp_max_syn_backlog=16384
    ulimits:
      memlock: -1
      nofile:
        soft: 100000
        hard: 100000
    security_opt:
      - seccomp:unconfined
    deploy:
      resources:
        limits:
          memory: 512M 
          cpus: '1.0'

  db:
    build:
      context: .data
      dockerfile: Dockerfiledb
    container_name: db
    volumes:
      - pg_data:/data
      - dbsocket:/tmp # Ubicación del socket
    restart: unless-stopped
    healthcheck:
      # Verificamos que el socket esté creado y responda
      test: ["CMD", "postgres", "-V"]
      interval: 5s
      timeout: 3s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'

volumes:
  pg_data:
  dbsocket:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=64m,mode=1777"