services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - db
    sysctls:
      - net.core.somaxconn=65535
      - net.ipv4.tcp_tw_reuse=1
      - net.ipv4.ip_local_port_range=1024 65535
      - net.ipv4.tcp_max_syn_backlog=16384
    ulimits:
      memlock: -1
      nofile:
        soft: 100000
        hard: 100000
    security_opt:
      - seccomp:unconfined
    deploy:
      resources:
        limits:
          memory: 512M 
          cpus: '1.0'

  db:
    build:
      context: ./data  # Apunta a la carpeta donde pusiste el nuevo Dockerfile
      dockerfile: Dockerfile
    container_name: postgres_db
    # IMPORTANTE: Si es la primera vez, el volumen debe inicializarse.
    # Como es scratch, si /data está vacío, fallará. 
    # Se recomienda usar un volumen nombrado para que Docker preserve los datos.
    volumes:
      - pg_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "postgres", "-V"] # Verificación mínima en scratch
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_data: # Volumen persistente gestionado por Docker